name: Update Google IMA Merged

on:
  workflow_dispatch:
    inputs:
      arg1:
        description: "iOS Version"
        required: true
        default: ""
      arg2:
        description: "tvOS Version"
        required: true
        default: ""

jobs:
  run-updater:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Run the Updater with Arguments
        run: bash ./Tools/update.bash "${{ github.event.inputs.arg1 }}" "${{ github.event.inputs.arg2 }}"

      - name: Zip the XCFramework
        run: |
          zip -r GoogleInteractiveMediaAds.zip ./.release/Product/GoogleInteractiveMediaAdsMerged.xcframework

      - name: Move Zip to Resources Directory
        run: |
          rm -rf ./Resources
          mkdir -p ./Resources
          mv GoogleInteractiveMediaAds.zip ./Resources/GoogleInteractiveMediaAds.zip

      - name: Generate Checksum
        id: checksum
        run: |
          echo "CHECKSUM=$(sha256sum ./Resources/GoogleInteractiveMediaAds.zip | awk '{print $1}')" >> $GITHUB_ENV

      - name: Delete .release Directory
        run: rm -rf ./.release

      - name: Commit Changes
        run: |
          git config --global user.name 'github-actions[bot]'
          git config --global user.email 'github-actions[bot]@users.noreply.github.com'
          git checkout -b update-ios-${{github.event.inputs.arg1}}-tvos-${{github.event.inputs.arg2}}
          git add ./Resources/GoogleInteractiveMediaAds.zip
          git commit -m "Add GoogleInteractiveMediaAds.zip to Resources"
          git push -u origin update-ios-${{github.event.inputs.arg1}}-tvos-${{github.event.inputs.arg2}}

      - name: Create Pull Request
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          gh pr create --title "Update GoogleInteractiveMediaAds.zip" --body "This PR updates the GoogleInteractiveMediaAds.zip with iOS: `${{ github.event.inputs.arg1 }}` and tvOS: `${{ github.event.inputs.arg2 }}` Checksum: `${{ env.CHECKSUM }}`" --head update-ios-${{github.event.inputs.arg1}}-tvos-${{github.event.inputs.arg2}} --base main
